// CONSTANTS NOT REQUIRED BUT ALLOW FOR BETTER ERROR HANDLING AND ASSIST IN PREVENTING SPELLING NEMESIS

export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_PEBBLE_STATE_CHANGE = 'USER_PEBBLE_STATE_CHANGE'